spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:32768/microservice_bank_news
    driver-class-name: org.postgresql.Driver
    username: postgres
    password:
    platform: POSTGRESQL
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  output:
    ansi:
      enabled: always
  application:
    name: bank-news
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8090/eureka
